[package]
name = "line_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# [workspace]
# members = ["line_parser"]

[lib]
name = "line_parser"
crate-type = ["lib"]
